[build]
  command = "mkdir -p netlify/functions/streamlit && pip install -r requirements.txt -t farm-finance/netlify/functions/streamlit/lib"
  functions = "farm-finance/netlify/functions"
  publish = "."

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/streamlit"
  status = 200
